// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kmed/api/ent/consultation"
	"kmed/api/ent/patient"
	"kmed/api/ent/schema"
	"kmed/api/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConsultationCreate is the builder for creating a Consultation entity.
type ConsultationCreate struct {
	config
	mutation *ConsultationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConsultationCreate) SetCreatedAt(v time.Time) *ConsultationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConsultationCreate) SetNillableCreatedAt(v *time.Time) *ConsultationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConsultationCreate) SetUpdatedAt(v time.Time) *ConsultationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConsultationCreate) SetNillableUpdatedAt(v *time.Time) *ConsultationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetVitals sets the "vitals" field.
func (_c *ConsultationCreate) SetVitals(v *schema.Vitals) *ConsultationCreate {
	_c.mutation.SetVitals(v)
	return _c
}

// SetClinicalNotes sets the "clinical_notes" field.
func (_c *ConsultationCreate) SetClinicalNotes(v *schema.ClinicalNotes) *ConsultationCreate {
	_c.mutation.SetClinicalNotes(v)
	return _c
}

// SetDiagnosis sets the "diagnosis" field.
func (_c *ConsultationCreate) SetDiagnosis(v *schema.Diagnosis) *ConsultationCreate {
	_c.mutation.SetDiagnosis(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ConsultationCreate) SetID(v uuid.UUID) *ConsultationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ConsultationCreate) SetNillableID(v *uuid.UUID) *ConsultationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPatientID sets the "patient" edge to the Patient entity by ID.
func (_c *ConsultationCreate) SetPatientID(id uuid.UUID) *ConsultationCreate {
	_c.mutation.SetPatientID(id)
	return _c
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_c *ConsultationCreate) SetPatient(v *Patient) *ConsultationCreate {
	return _c.SetPatientID(v.ID)
}

// SetDoctorID sets the "doctor" edge to the User entity by ID.
func (_c *ConsultationCreate) SetDoctorID(id uuid.UUID) *ConsultationCreate {
	_c.mutation.SetDoctorID(id)
	return _c
}

// SetDoctor sets the "doctor" edge to the User entity.
func (_c *ConsultationCreate) SetDoctor(v *User) *ConsultationCreate {
	return _c.SetDoctorID(v.ID)
}

// Mutation returns the ConsultationMutation object of the builder.
func (_c *ConsultationCreate) Mutation() *ConsultationMutation {
	return _c.mutation
}

// Save creates the Consultation in the database.
func (_c *ConsultationCreate) Save(ctx context.Context) (*Consultation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConsultationCreate) SaveX(ctx context.Context) *Consultation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConsultationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConsultationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConsultationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := consultation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := consultation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := consultation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConsultationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Consultation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Consultation.updated_at"`)}
	}
	if _, ok := _c.mutation.Vitals(); !ok {
		return &ValidationError{Name: "vitals", err: errors.New(`ent: missing required field "Consultation.vitals"`)}
	}
	if _, ok := _c.mutation.ClinicalNotes(); !ok {
		return &ValidationError{Name: "clinical_notes", err: errors.New(`ent: missing required field "Consultation.clinical_notes"`)}
	}
	if _, ok := _c.mutation.Diagnosis(); !ok {
		return &ValidationError{Name: "diagnosis", err: errors.New(`ent: missing required field "Consultation.diagnosis"`)}
	}
	if len(_c.mutation.PatientIDs()) == 0 {
		return &ValidationError{Name: "patient", err: errors.New(`ent: missing required edge "Consultation.patient"`)}
	}
	if len(_c.mutation.DoctorIDs()) == 0 {
		return &ValidationError{Name: "doctor", err: errors.New(`ent: missing required edge "Consultation.doctor"`)}
	}
	return nil
}

func (_c *ConsultationCreate) sqlSave(ctx context.Context) (*Consultation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConsultationCreate) createSpec() (*Consultation, *sqlgraph.CreateSpec) {
	var (
		_node = &Consultation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(consultation.Table, sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(consultation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(consultation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Vitals(); ok {
		_spec.SetField(consultation.FieldVitals, field.TypeJSON, value)
		_node.Vitals = value
	}
	if value, ok := _c.mutation.ClinicalNotes(); ok {
		_spec.SetField(consultation.FieldClinicalNotes, field.TypeJSON, value)
		_node.ClinicalNotes = value
	}
	if value, ok := _c.mutation.Diagnosis(); ok {
		_spec.SetField(consultation.FieldDiagnosis, field.TypeJSON, value)
		_node.Diagnosis = value
	}
	if nodes := _c.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.PatientTable,
			Columns: []string{consultation.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.patient_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.DoctorTable,
			Columns: []string{consultation.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.doctor_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConsultationCreateBulk is the builder for creating many Consultation entities in bulk.
type ConsultationCreateBulk struct {
	config
	err      error
	builders []*ConsultationCreate
}

// Save creates the Consultation entities in the database.
func (_c *ConsultationCreateBulk) Save(ctx context.Context) ([]*Consultation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Consultation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConsultationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConsultationCreateBulk) SaveX(ctx context.Context) []*Consultation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConsultationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConsultationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
