// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kmed/api/ent/consultation"
	"kmed/api/ent/patient"
	"kmed/api/ent/predicate"
	"kmed/api/ent/schema"
	"kmed/api/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConsultationUpdate is the builder for updating Consultation entities.
type ConsultationUpdate struct {
	config
	hooks    []Hook
	mutation *ConsultationMutation
}

// Where appends a list predicates to the ConsultationUpdate builder.
func (_u *ConsultationUpdate) Where(ps ...predicate.Consultation) *ConsultationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConsultationUpdate) SetUpdatedAt(v time.Time) *ConsultationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVitals sets the "vitals" field.
func (_u *ConsultationUpdate) SetVitals(v *schema.Vitals) *ConsultationUpdate {
	_u.mutation.SetVitals(v)
	return _u
}

// SetClinicalNotes sets the "clinical_notes" field.
func (_u *ConsultationUpdate) SetClinicalNotes(v *schema.ClinicalNotes) *ConsultationUpdate {
	_u.mutation.SetClinicalNotes(v)
	return _u
}

// SetDiagnosis sets the "diagnosis" field.
func (_u *ConsultationUpdate) SetDiagnosis(v *schema.Diagnosis) *ConsultationUpdate {
	_u.mutation.SetDiagnosis(v)
	return _u
}

// SetPatientID sets the "patient" edge to the Patient entity by ID.
func (_u *ConsultationUpdate) SetPatientID(id uuid.UUID) *ConsultationUpdate {
	_u.mutation.SetPatientID(id)
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *ConsultationUpdate) SetPatient(v *Patient) *ConsultationUpdate {
	return _u.SetPatientID(v.ID)
}

// SetDoctorID sets the "doctor" edge to the User entity by ID.
func (_u *ConsultationUpdate) SetDoctorID(id uuid.UUID) *ConsultationUpdate {
	_u.mutation.SetDoctorID(id)
	return _u
}

// SetDoctor sets the "doctor" edge to the User entity.
func (_u *ConsultationUpdate) SetDoctor(v *User) *ConsultationUpdate {
	return _u.SetDoctorID(v.ID)
}

// Mutation returns the ConsultationMutation object of the builder.
func (_u *ConsultationUpdate) Mutation() *ConsultationMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *ConsultationUpdate) ClearPatient() *ConsultationUpdate {
	_u.mutation.ClearPatient()
	return _u
}

// ClearDoctor clears the "doctor" edge to the User entity.
func (_u *ConsultationUpdate) ClearDoctor() *ConsultationUpdate {
	_u.mutation.ClearDoctor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConsultationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConsultationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConsultationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConsultationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConsultationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := consultation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConsultationUpdate) check() error {
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Consultation.patient"`)
	}
	if _u.mutation.DoctorCleared() && len(_u.mutation.DoctorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Consultation.doctor"`)
	}
	return nil
}

func (_u *ConsultationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consultation.Table, consultation.Columns, sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(consultation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Vitals(); ok {
		_spec.SetField(consultation.FieldVitals, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ClinicalNotes(); ok {
		_spec.SetField(consultation.FieldClinicalNotes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Diagnosis(); ok {
		_spec.SetField(consultation.FieldDiagnosis, field.TypeJSON, value)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.PatientTable,
			Columns: []string{consultation.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.PatientTable,
			Columns: []string{consultation.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.DoctorTable,
			Columns: []string{consultation.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.DoctorTable,
			Columns: []string{consultation.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consultation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConsultationUpdateOne is the builder for updating a single Consultation entity.
type ConsultationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConsultationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConsultationUpdateOne) SetUpdatedAt(v time.Time) *ConsultationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVitals sets the "vitals" field.
func (_u *ConsultationUpdateOne) SetVitals(v *schema.Vitals) *ConsultationUpdateOne {
	_u.mutation.SetVitals(v)
	return _u
}

// SetClinicalNotes sets the "clinical_notes" field.
func (_u *ConsultationUpdateOne) SetClinicalNotes(v *schema.ClinicalNotes) *ConsultationUpdateOne {
	_u.mutation.SetClinicalNotes(v)
	return _u
}

// SetDiagnosis sets the "diagnosis" field.
func (_u *ConsultationUpdateOne) SetDiagnosis(v *schema.Diagnosis) *ConsultationUpdateOne {
	_u.mutation.SetDiagnosis(v)
	return _u
}

// SetPatientID sets the "patient" edge to the Patient entity by ID.
func (_u *ConsultationUpdateOne) SetPatientID(id uuid.UUID) *ConsultationUpdateOne {
	_u.mutation.SetPatientID(id)
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *ConsultationUpdateOne) SetPatient(v *Patient) *ConsultationUpdateOne {
	return _u.SetPatientID(v.ID)
}

// SetDoctorID sets the "doctor" edge to the User entity by ID.
func (_u *ConsultationUpdateOne) SetDoctorID(id uuid.UUID) *ConsultationUpdateOne {
	_u.mutation.SetDoctorID(id)
	return _u
}

// SetDoctor sets the "doctor" edge to the User entity.
func (_u *ConsultationUpdateOne) SetDoctor(v *User) *ConsultationUpdateOne {
	return _u.SetDoctorID(v.ID)
}

// Mutation returns the ConsultationMutation object of the builder.
func (_u *ConsultationUpdateOne) Mutation() *ConsultationMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *ConsultationUpdateOne) ClearPatient() *ConsultationUpdateOne {
	_u.mutation.ClearPatient()
	return _u
}

// ClearDoctor clears the "doctor" edge to the User entity.
func (_u *ConsultationUpdateOne) ClearDoctor() *ConsultationUpdateOne {
	_u.mutation.ClearDoctor()
	return _u
}

// Where appends a list predicates to the ConsultationUpdate builder.
func (_u *ConsultationUpdateOne) Where(ps ...predicate.Consultation) *ConsultationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConsultationUpdateOne) Select(field string, fields ...string) *ConsultationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Consultation entity.
func (_u *ConsultationUpdateOne) Save(ctx context.Context) (*Consultation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConsultationUpdateOne) SaveX(ctx context.Context) *Consultation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConsultationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConsultationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConsultationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := consultation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConsultationUpdateOne) check() error {
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Consultation.patient"`)
	}
	if _u.mutation.DoctorCleared() && len(_u.mutation.DoctorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Consultation.doctor"`)
	}
	return nil
}

func (_u *ConsultationUpdateOne) sqlSave(ctx context.Context) (_node *Consultation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consultation.Table, consultation.Columns, sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Consultation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, consultation.FieldID)
		for _, f := range fields {
			if !consultation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != consultation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(consultation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Vitals(); ok {
		_spec.SetField(consultation.FieldVitals, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ClinicalNotes(); ok {
		_spec.SetField(consultation.FieldClinicalNotes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Diagnosis(); ok {
		_spec.SetField(consultation.FieldDiagnosis, field.TypeJSON, value)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.PatientTable,
			Columns: []string{consultation.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.PatientTable,
			Columns: []string{consultation.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.DoctorTable,
			Columns: []string{consultation.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consultation.DoctorTable,
			Columns: []string{consultation.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Consultation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consultation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
