// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConsultationsColumns holds the columns for the "consultations" table.
	ConsultationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "vitals", Type: field.TypeJSON},
		{Name: "clinical_notes", Type: field.TypeJSON},
		{Name: "diagnosis", Type: field.TypeJSON},
		{Name: "patient_id", Type: field.TypeUUID},
		{Name: "doctor_id", Type: field.TypeUUID},
	}
	// ConsultationsTable holds the schema information for the "consultations" table.
	ConsultationsTable = &schema.Table{
		Name:       "consultations",
		Columns:    ConsultationsColumns,
		PrimaryKey: []*schema.Column{ConsultationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "consultations_patients_consultations",
				Columns:    []*schema.Column{ConsultationsColumns[6]},
				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "consultations_users_consultations",
				Columns:    []*schema.Column{ConsultationsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "phone_number", Type: field.TypeString, Nullable: true},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"male", "female", "unspecified"}, Default: "unspecified"},
		{Name: "marital_status", Type: field.TypeEnum, Enums: []string{"married", "single", "unspecified"}, Default: "unspecified"},
		{Name: "dob", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:       "patients",
		Columns:    PatientsColumns,
		PrimaryKey: []*schema.Column{PatientsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "doctor", "lab-tech", "user"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConsultationsTable,
		PatientsTable,
		UsersTable,
	}
)

func init() {
	ConsultationsTable.ForeignKeys[0].RefTable = PatientsTable
	ConsultationsTable.ForeignKeys[1].RefTable = UsersTable
}
