// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"kmed/api/ent/consultation"
	"kmed/api/ent/patient"
	"kmed/api/ent/schema"
	"kmed/api/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Consultation is the model entity for the Consultation schema.
type Consultation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Vitals holds the value of the "vitals" field.
	Vitals *schema.Vitals `json:"vitals,omitempty"`
	// ClinicalNotes holds the value of the "clinical_notes" field.
	ClinicalNotes *schema.ClinicalNotes `json:"clinical_notes,omitempty"`
	// Diagnosis holds the value of the "diagnosis" field.
	Diagnosis *schema.Diagnosis `json:"diagnosis,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConsultationQuery when eager-loading is set.
	Edges        ConsultationEdges `json:"edges"`
	patient_id   *uuid.UUID
	doctor_id    *uuid.UUID
	selectValues sql.SelectValues
}

// ConsultationEdges holds the relations/edges for other nodes in the graph.
type ConsultationEdges struct {
	// Patient holds the value of the patient edge.
	Patient *Patient `json:"patient,omitempty"`
	// Doctor holds the value of the doctor edge.
	Doctor *User `json:"doctor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PatientOrErr returns the Patient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConsultationEdges) PatientOrErr() (*Patient, error) {
	if e.Patient != nil {
		return e.Patient, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: patient.Label}
	}
	return nil, &NotLoadedError{edge: "patient"}
}

// DoctorOrErr returns the Doctor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConsultationEdges) DoctorOrErr() (*User, error) {
	if e.Doctor != nil {
		return e.Doctor, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "doctor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Consultation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case consultation.FieldVitals, consultation.FieldClinicalNotes, consultation.FieldDiagnosis:
			values[i] = new([]byte)
		case consultation.FieldCreatedAt, consultation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case consultation.FieldID:
			values[i] = new(uuid.UUID)
		case consultation.ForeignKeys[0]: // patient_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case consultation.ForeignKeys[1]: // doctor_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Consultation fields.
func (_m *Consultation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case consultation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case consultation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case consultation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case consultation.FieldVitals:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field vitals", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Vitals); err != nil {
					return fmt.Errorf("unmarshal field vitals: %w", err)
				}
			}
		case consultation.FieldClinicalNotes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field clinical_notes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ClinicalNotes); err != nil {
					return fmt.Errorf("unmarshal field clinical_notes: %w", err)
				}
			}
		case consultation.FieldDiagnosis:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field diagnosis", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Diagnosis); err != nil {
					return fmt.Errorf("unmarshal field diagnosis: %w", err)
				}
			}
		case consultation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field patient_id", values[i])
			} else if value.Valid {
				_m.patient_id = new(uuid.UUID)
				*_m.patient_id = *value.S.(*uuid.UUID)
			}
		case consultation.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field doctor_id", values[i])
			} else if value.Valid {
				_m.doctor_id = new(uuid.UUID)
				*_m.doctor_id = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Consultation.
// This includes values selected through modifiers, order, etc.
func (_m *Consultation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPatient queries the "patient" edge of the Consultation entity.
func (_m *Consultation) QueryPatient() *PatientQuery {
	return NewConsultationClient(_m.config).QueryPatient(_m)
}

// QueryDoctor queries the "doctor" edge of the Consultation entity.
func (_m *Consultation) QueryDoctor() *UserQuery {
	return NewConsultationClient(_m.config).QueryDoctor(_m)
}

// Update returns a builder for updating this Consultation.
// Note that you need to call Consultation.Unwrap() before calling this method if this Consultation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Consultation) Update() *ConsultationUpdateOne {
	return NewConsultationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Consultation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Consultation) Unwrap() *Consultation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Consultation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Consultation) String() string {
	var builder strings.Builder
	builder.WriteString("Consultation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("vitals=")
	builder.WriteString(fmt.Sprintf("%v", _m.Vitals))
	builder.WriteString(", ")
	builder.WriteString("clinical_notes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClinicalNotes))
	builder.WriteString(", ")
	builder.WriteString("diagnosis=")
	builder.WriteString(fmt.Sprintf("%v", _m.Diagnosis))
	builder.WriteByte(')')
	return builder.String()
}

// Consultations is a parsable slice of Consultation.
type Consultations []*Consultation
