// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kmed/api/ent/consultation"
	"kmed/api/ent/patient"
	"kmed/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PatientUpdate is the builder for updating Patient entities.
type PatientUpdate struct {
	config
	hooks    []Hook
	mutation *PatientMutation
}

// Where appends a list predicates to the PatientUpdate builder.
func (_u *PatientUpdate) Where(ps ...predicate.Patient) *PatientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PatientUpdate) SetUpdatedAt(v time.Time) *PatientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PatientUpdate) SetName(v string) *PatientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PatientUpdate) SetNillableName(v *string) *PatientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *PatientUpdate) SetPhoneNumber(v string) *PatientUpdate {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *PatientUpdate) SetNillablePhoneNumber(v *string) *PatientUpdate {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (_u *PatientUpdate) ClearPhoneNumber() *PatientUpdate {
	_u.mutation.ClearPhoneNumber()
	return _u
}

// SetGender sets the "gender" field.
func (_u *PatientUpdate) SetGender(v patient.Gender) *PatientUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *PatientUpdate) SetNillableGender(v *patient.Gender) *PatientUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// SetMaritalStatus sets the "marital_status" field.
func (_u *PatientUpdate) SetMaritalStatus(v patient.MaritalStatus) *PatientUpdate {
	_u.mutation.SetMaritalStatus(v)
	return _u
}

// SetNillableMaritalStatus sets the "marital_status" field if the given value is not nil.
func (_u *PatientUpdate) SetNillableMaritalStatus(v *patient.MaritalStatus) *PatientUpdate {
	if v != nil {
		_u.SetMaritalStatus(*v)
	}
	return _u
}

// SetDob sets the "dob" field.
func (_u *PatientUpdate) SetDob(v time.Time) *PatientUpdate {
	_u.mutation.SetDob(v)
	return _u
}

// SetNillableDob sets the "dob" field if the given value is not nil.
func (_u *PatientUpdate) SetNillableDob(v *time.Time) *PatientUpdate {
	if v != nil {
		_u.SetDob(*v)
	}
	return _u
}

// ClearDob clears the value of the "dob" field.
func (_u *PatientUpdate) ClearDob() *PatientUpdate {
	_u.mutation.ClearDob()
	return _u
}

// SetEmail sets the "email" field.
func (_u *PatientUpdate) SetEmail(v string) *PatientUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PatientUpdate) SetNillableEmail(v *string) *PatientUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *PatientUpdate) ClearEmail() *PatientUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// AddConsultationIDs adds the "consultations" edge to the Consultation entity by IDs.
func (_u *PatientUpdate) AddConsultationIDs(ids ...uuid.UUID) *PatientUpdate {
	_u.mutation.AddConsultationIDs(ids...)
	return _u
}

// AddConsultations adds the "consultations" edges to the Consultation entity.
func (_u *PatientUpdate) AddConsultations(v ...*Consultation) *PatientUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConsultationIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (_u *PatientUpdate) Mutation() *PatientMutation {
	return _u.mutation
}

// ClearConsultations clears all "consultations" edges to the Consultation entity.
func (_u *PatientUpdate) ClearConsultations() *PatientUpdate {
	_u.mutation.ClearConsultations()
	return _u
}

// RemoveConsultationIDs removes the "consultations" edge to Consultation entities by IDs.
func (_u *PatientUpdate) RemoveConsultationIDs(ids ...uuid.UUID) *PatientUpdate {
	_u.mutation.RemoveConsultationIDs(ids...)
	return _u
}

// RemoveConsultations removes "consultations" edges to Consultation entities.
func (_u *PatientUpdate) RemoveConsultations(v ...*Consultation) *PatientUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConsultationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PatientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PatientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PatientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := patient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PatientUpdate) check() error {
	if v, ok := _u.mutation.PhoneNumber(); ok {
		if err := patient.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Patient.phone_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := patient.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Patient.gender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaritalStatus(); ok {
		if err := patient.MaritalStatusValidator(v); err != nil {
			return &ValidationError{Name: "marital_status", err: fmt.Errorf(`ent: validator failed for field "Patient.marital_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := patient.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Patient.email": %w`, err)}
		}
	}
	return nil
}

func (_u *PatientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(patient.Table, patient.Columns, sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(patient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(patient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(patient.FieldPhoneNumber, field.TypeString, value)
	}
	if _u.mutation.PhoneNumberCleared() {
		_spec.ClearField(patient.FieldPhoneNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(patient.FieldGender, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaritalStatus(); ok {
		_spec.SetField(patient.FieldMaritalStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Dob(); ok {
		_spec.SetField(patient.FieldDob, field.TypeTime, value)
	}
	if _u.mutation.DobCleared() {
		_spec.ClearField(patient.FieldDob, field.TypeTime)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(patient.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(patient.FieldEmail, field.TypeString)
	}
	if _u.mutation.ConsultationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConsultationsIDs(); len(nodes) > 0 && !_u.mutation.ConsultationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsultationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PatientUpdateOne is the builder for updating a single Patient entity.
type PatientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PatientMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PatientUpdateOne) SetUpdatedAt(v time.Time) *PatientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PatientUpdateOne) SetName(v string) *PatientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PatientUpdateOne) SetNillableName(v *string) *PatientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *PatientUpdateOne) SetPhoneNumber(v string) *PatientUpdateOne {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *PatientUpdateOne) SetNillablePhoneNumber(v *string) *PatientUpdateOne {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (_u *PatientUpdateOne) ClearPhoneNumber() *PatientUpdateOne {
	_u.mutation.ClearPhoneNumber()
	return _u
}

// SetGender sets the "gender" field.
func (_u *PatientUpdateOne) SetGender(v patient.Gender) *PatientUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *PatientUpdateOne) SetNillableGender(v *patient.Gender) *PatientUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// SetMaritalStatus sets the "marital_status" field.
func (_u *PatientUpdateOne) SetMaritalStatus(v patient.MaritalStatus) *PatientUpdateOne {
	_u.mutation.SetMaritalStatus(v)
	return _u
}

// SetNillableMaritalStatus sets the "marital_status" field if the given value is not nil.
func (_u *PatientUpdateOne) SetNillableMaritalStatus(v *patient.MaritalStatus) *PatientUpdateOne {
	if v != nil {
		_u.SetMaritalStatus(*v)
	}
	return _u
}

// SetDob sets the "dob" field.
func (_u *PatientUpdateOne) SetDob(v time.Time) *PatientUpdateOne {
	_u.mutation.SetDob(v)
	return _u
}

// SetNillableDob sets the "dob" field if the given value is not nil.
func (_u *PatientUpdateOne) SetNillableDob(v *time.Time) *PatientUpdateOne {
	if v != nil {
		_u.SetDob(*v)
	}
	return _u
}

// ClearDob clears the value of the "dob" field.
func (_u *PatientUpdateOne) ClearDob() *PatientUpdateOne {
	_u.mutation.ClearDob()
	return _u
}

// SetEmail sets the "email" field.
func (_u *PatientUpdateOne) SetEmail(v string) *PatientUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PatientUpdateOne) SetNillableEmail(v *string) *PatientUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *PatientUpdateOne) ClearEmail() *PatientUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// AddConsultationIDs adds the "consultations" edge to the Consultation entity by IDs.
func (_u *PatientUpdateOne) AddConsultationIDs(ids ...uuid.UUID) *PatientUpdateOne {
	_u.mutation.AddConsultationIDs(ids...)
	return _u
}

// AddConsultations adds the "consultations" edges to the Consultation entity.
func (_u *PatientUpdateOne) AddConsultations(v ...*Consultation) *PatientUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConsultationIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (_u *PatientUpdateOne) Mutation() *PatientMutation {
	return _u.mutation
}

// ClearConsultations clears all "consultations" edges to the Consultation entity.
func (_u *PatientUpdateOne) ClearConsultations() *PatientUpdateOne {
	_u.mutation.ClearConsultations()
	return _u
}

// RemoveConsultationIDs removes the "consultations" edge to Consultation entities by IDs.
func (_u *PatientUpdateOne) RemoveConsultationIDs(ids ...uuid.UUID) *PatientUpdateOne {
	_u.mutation.RemoveConsultationIDs(ids...)
	return _u
}

// RemoveConsultations removes "consultations" edges to Consultation entities.
func (_u *PatientUpdateOne) RemoveConsultations(v ...*Consultation) *PatientUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConsultationIDs(ids...)
}

// Where appends a list predicates to the PatientUpdate builder.
func (_u *PatientUpdateOne) Where(ps ...predicate.Patient) *PatientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PatientUpdateOne) Select(field string, fields ...string) *PatientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Patient entity.
func (_u *PatientUpdateOne) Save(ctx context.Context) (*Patient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatientUpdateOne) SaveX(ctx context.Context) *Patient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PatientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PatientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := patient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PatientUpdateOne) check() error {
	if v, ok := _u.mutation.PhoneNumber(); ok {
		if err := patient.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Patient.phone_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := patient.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Patient.gender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaritalStatus(); ok {
		if err := patient.MaritalStatusValidator(v); err != nil {
			return &ValidationError{Name: "marital_status", err: fmt.Errorf(`ent: validator failed for field "Patient.marital_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := patient.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Patient.email": %w`, err)}
		}
	}
	return nil
}

func (_u *PatientUpdateOne) sqlSave(ctx context.Context) (_node *Patient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(patient.Table, patient.Columns, sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Patient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, patient.FieldID)
		for _, f := range fields {
			if !patient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != patient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(patient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(patient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(patient.FieldPhoneNumber, field.TypeString, value)
	}
	if _u.mutation.PhoneNumberCleared() {
		_spec.ClearField(patient.FieldPhoneNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(patient.FieldGender, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaritalStatus(); ok {
		_spec.SetField(patient.FieldMaritalStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Dob(); ok {
		_spec.SetField(patient.FieldDob, field.TypeTime, value)
	}
	if _u.mutation.DobCleared() {
		_spec.ClearField(patient.FieldDob, field.TypeTime)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(patient.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(patient.FieldEmail, field.TypeString)
	}
	if _u.mutation.ConsultationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConsultationsIDs(); len(nodes) > 0 && !_u.mutation.ConsultationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsultationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Patient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
