// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kmed/api/ent/consultation"
	"kmed/api/ent/patient"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PatientCreate is the builder for creating a Patient entity.
type PatientCreate struct {
	config
	mutation *PatientMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PatientCreate) SetCreatedAt(v time.Time) *PatientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PatientCreate) SetNillableCreatedAt(v *time.Time) *PatientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PatientCreate) SetUpdatedAt(v time.Time) *PatientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PatientCreate) SetNillableUpdatedAt(v *time.Time) *PatientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PatientCreate) SetName(v string) *PatientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPhoneNumber sets the "phone_number" field.
func (_c *PatientCreate) SetPhoneNumber(v string) *PatientCreate {
	_c.mutation.SetPhoneNumber(v)
	return _c
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_c *PatientCreate) SetNillablePhoneNumber(v *string) *PatientCreate {
	if v != nil {
		_c.SetPhoneNumber(*v)
	}
	return _c
}

// SetGender sets the "gender" field.
func (_c *PatientCreate) SetGender(v patient.Gender) *PatientCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_c *PatientCreate) SetNillableGender(v *patient.Gender) *PatientCreate {
	if v != nil {
		_c.SetGender(*v)
	}
	return _c
}

// SetMaritalStatus sets the "marital_status" field.
func (_c *PatientCreate) SetMaritalStatus(v patient.MaritalStatus) *PatientCreate {
	_c.mutation.SetMaritalStatus(v)
	return _c
}

// SetNillableMaritalStatus sets the "marital_status" field if the given value is not nil.
func (_c *PatientCreate) SetNillableMaritalStatus(v *patient.MaritalStatus) *PatientCreate {
	if v != nil {
		_c.SetMaritalStatus(*v)
	}
	return _c
}

// SetDob sets the "dob" field.
func (_c *PatientCreate) SetDob(v time.Time) *PatientCreate {
	_c.mutation.SetDob(v)
	return _c
}

// SetNillableDob sets the "dob" field if the given value is not nil.
func (_c *PatientCreate) SetNillableDob(v *time.Time) *PatientCreate {
	if v != nil {
		_c.SetDob(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *PatientCreate) SetEmail(v string) *PatientCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *PatientCreate) SetNillableEmail(v *string) *PatientCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PatientCreate) SetID(v uuid.UUID) *PatientCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PatientCreate) SetNillableID(v *uuid.UUID) *PatientCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddConsultationIDs adds the "consultations" edge to the Consultation entity by IDs.
func (_c *PatientCreate) AddConsultationIDs(ids ...uuid.UUID) *PatientCreate {
	_c.mutation.AddConsultationIDs(ids...)
	return _c
}

// AddConsultations adds the "consultations" edges to the Consultation entity.
func (_c *PatientCreate) AddConsultations(v ...*Consultation) *PatientCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConsultationIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (_c *PatientCreate) Mutation() *PatientMutation {
	return _c.mutation
}

// Save creates the Patient in the database.
func (_c *PatientCreate) Save(ctx context.Context) (*Patient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PatientCreate) SaveX(ctx context.Context) *Patient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PatientCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := patient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := patient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Gender(); !ok {
		v := patient.DefaultGender
		_c.mutation.SetGender(v)
	}
	if _, ok := _c.mutation.MaritalStatus(); !ok {
		v := patient.DefaultMaritalStatus
		_c.mutation.SetMaritalStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := patient.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PatientCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Patient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Patient.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Patient.name"`)}
	}
	if v, ok := _c.mutation.PhoneNumber(); ok {
		if err := patient.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Patient.phone_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Gender(); !ok {
		return &ValidationError{Name: "gender", err: errors.New(`ent: missing required field "Patient.gender"`)}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := patient.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Patient.gender": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaritalStatus(); !ok {
		return &ValidationError{Name: "marital_status", err: errors.New(`ent: missing required field "Patient.marital_status"`)}
	}
	if v, ok := _c.mutation.MaritalStatus(); ok {
		if err := patient.MaritalStatusValidator(v); err != nil {
			return &ValidationError{Name: "marital_status", err: fmt.Errorf(`ent: validator failed for field "Patient.marital_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := patient.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Patient.email": %w`, err)}
		}
	}
	return nil
}

func (_c *PatientCreate) sqlSave(ctx context.Context) (*Patient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PatientCreate) createSpec() (*Patient, *sqlgraph.CreateSpec) {
	var (
		_node = &Patient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(patient.Table, sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(patient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(patient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(patient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PhoneNumber(); ok {
		_spec.SetField(patient.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(patient.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.MaritalStatus(); ok {
		_spec.SetField(patient.FieldMaritalStatus, field.TypeEnum, value)
		_node.MaritalStatus = value
	}
	if value, ok := _c.mutation.Dob(); ok {
		_spec.SetField(patient.FieldDob, field.TypeTime, value)
		_node.Dob = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(patient.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if nodes := _c.mutation.ConsultationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.ConsultationsTable,
			Columns: []string{patient.ConsultationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consultation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PatientCreateBulk is the builder for creating many Patient entities in bulk.
type PatientCreateBulk struct {
	config
	err      error
	builders []*PatientCreate
}

// Save creates the Patient entities in the database.
func (_c *PatientCreateBulk) Save(ctx context.Context) ([]*Patient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Patient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PatientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PatientCreateBulk) SaveX(ctx context.Context) []*Patient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
