// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kmed/api/ent/consultation"
	"kmed/api/ent/patient"
	"kmed/api/ent/schema"
	"kmed/api/ent/session"
	"kmed/api/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	consultationMixin := schema.Consultation{}.Mixin()
	consultationMixinFields0 := consultationMixin[0].Fields()
	_ = consultationMixinFields0
	consultationFields := schema.Consultation{}.Fields()
	_ = consultationFields
	// consultationDescCreatedAt is the schema descriptor for created_at field.
	consultationDescCreatedAt := consultationMixinFields0[0].Descriptor()
	// consultation.DefaultCreatedAt holds the default value on creation for the created_at field.
	consultation.DefaultCreatedAt = consultationDescCreatedAt.Default.(func() time.Time)
	// consultationDescUpdatedAt is the schema descriptor for updated_at field.
	consultationDescUpdatedAt := consultationMixinFields0[1].Descriptor()
	// consultation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	consultation.DefaultUpdatedAt = consultationDescUpdatedAt.Default.(func() time.Time)
	// consultation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	consultation.UpdateDefaultUpdatedAt = consultationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// consultationDescID is the schema descriptor for id field.
	consultationDescID := consultationFields[0].Descriptor()
	// consultation.DefaultID holds the default value on creation for the id field.
	consultation.DefaultID = consultationDescID.Default.(func() uuid.UUID)
	patientMixin := schema.Patient{}.Mixin()
	patientMixinFields0 := patientMixin[0].Fields()
	_ = patientMixinFields0
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescCreatedAt is the schema descriptor for created_at field.
	patientDescCreatedAt := patientMixinFields0[0].Descriptor()
	// patient.DefaultCreatedAt holds the default value on creation for the created_at field.
	patient.DefaultCreatedAt = patientDescCreatedAt.Default.(func() time.Time)
	// patientDescUpdatedAt is the schema descriptor for updated_at field.
	patientDescUpdatedAt := patientMixinFields0[1].Descriptor()
	// patient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	patient.DefaultUpdatedAt = patientDescUpdatedAt.Default.(func() time.Time)
	// patient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	patient.UpdateDefaultUpdatedAt = patientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// patientDescPhoneNumber is the schema descriptor for phone_number field.
	patientDescPhoneNumber := patientFields[2].Descriptor()
	// patient.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	patient.PhoneNumberValidator = patientDescPhoneNumber.Validators[0].(func(string) error)
	// patientDescEmail is the schema descriptor for email field.
	patientDescEmail := patientFields[6].Descriptor()
	// patient.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	patient.EmailValidator = patientDescEmail.Validators[0].(func(string) error)
	// patientDescID is the schema descriptor for id field.
	patientDescID := patientFields[0].Descriptor()
	// patient.DefaultID holds the default value on creation for the id field.
	patient.DefaultID = patientDescID.Default.(func() uuid.UUID)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionMixinFields0[0].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionMixinFields0[1].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescRefreshTokenHash is the schema descriptor for refresh_token_hash field.
	sessionDescRefreshTokenHash := sessionFields[2].Descriptor()
	// session.RefreshTokenHashValidator is a validator for the "refresh_token_hash" field. It is called by the builders before save.
	session.RefreshTokenHashValidator = sessionDescRefreshTokenHash.Validators[0].(func(string) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescMustChangePassword is the schema descriptor for must_change_password field.
	userDescMustChangePassword := userFields[5].Descriptor()
	// user.DefaultMustChangePassword holds the default value on creation for the must_change_password field.
	user.DefaultMustChangePassword = userDescMustChangePassword.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
