/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppCtnRouteImport } from './routes/_app._ctn'
import { Route as AppPttRouteImport } from './routes/_app._ptt'
import { Route as AppUsrRouteImport } from './routes/_app._usr'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOnboardRouteImport } from './routes/_app.onboard'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthLogoutRouteImport } from './routes/_auth.logout'
import { Route as AuthQuitRouteImport } from './routes/_auth.quit'
import { Route as AppCtnConsultationsRouteImport } from './routes/_app._ctn.consultations'
import { Route as AppUsrNewUserRouteImport } from './routes/_app._usr.new-user'
import { Route as AppUsrUsersRouteImport } from './routes/_app._usr.users'
import { Route as AppCtnConsultationConsultationIdRouteImport } from './routes/_app._ctn.consultation.$consultationId'
import { Route as AppCtnConsultationStartRouteImport } from './routes/_app._ctn.consultation.start'
import { Route as AppPttPatientsNewRouteImport } from './routes/_app._ptt.patients.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCtnRoute = AppCtnRouteImport.update({
  id: '/_ctn',
  getParentRoute: () => AppRoute,
} as any)
const AppPttRoute = AppPttRouteImport.update({
  id: '/_ptt',
  getParentRoute: () => AppRoute,
} as any)
const AppUsrRoute = AppUsrRouteImport.update({
  id: '/_usr',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuitRoute = AuthQuitRouteImport.update({
  id: '/quit',
  path: '/quit',
  getParentRoute: () => AuthRoute,
} as any)
const AppCtnConsultationsRoute = AppCtnConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AppCtnRoute,
} as any)
const AppUsrNewUserRoute = AppUsrNewUserRouteImport.update({
  id: '/new-user',
  path: '/new-user',
  getParentRoute: () => AppUsrRoute,
} as any)
const AppUsrUsersRoute = AppUsrUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppUsrRoute,
} as any)
const AppCtnConsultationConsultationIdRoute =
  AppCtnConsultationConsultationIdRouteImport.update({
    id: '/consultation/$consultationId',
    path: '/consultation/$consultationId',
    getParentRoute: () => AppCtnRoute,
  } as any)
const AppCtnConsultationStartRoute = AppCtnConsultationStartRouteImport.update({
  id: '/consultation/start',
  path: '/consultation/start',
  getParentRoute: () => AppCtnRoute,
} as any)
const AppPttPatientsNewRoute = AppPttPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppPttRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboard': typeof AppOnboardRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/quit': typeof AuthQuitRoute
  '/consultations': typeof AppCtnConsultationsRoute
  '/new-user': typeof AppUsrNewUserRoute
  '/users': typeof AppUsrUsersRoute
  '/consultation/$consultationId': typeof AppCtnConsultationConsultationIdRoute
  '/consultation/start': typeof AppCtnConsultationStartRoute
  '/patients/new': typeof AppPttPatientsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboard': typeof AppOnboardRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/quit': typeof AuthQuitRoute
  '/consultations': typeof AppCtnConsultationsRoute
  '/new-user': typeof AppUsrNewUserRoute
  '/users': typeof AppUsrUsersRoute
  '/consultation/$consultationId': typeof AppCtnConsultationConsultationIdRoute
  '/consultation/start': typeof AppCtnConsultationStartRoute
  '/patients/new': typeof AppPttPatientsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_ctn': typeof AppCtnRouteWithChildren
  '/_app/_ptt': typeof AppPttRouteWithChildren
  '/_app/_usr': typeof AppUsrRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/onboard': typeof AppOnboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/quit': typeof AuthQuitRoute
  '/_app/_ctn/consultations': typeof AppCtnConsultationsRoute
  '/_app/_usr/new-user': typeof AppUsrNewUserRoute
  '/_app/_usr/users': typeof AppUsrUsersRoute
  '/_app/_ctn/consultation/$consultationId': typeof AppCtnConsultationConsultationIdRoute
  '/_app/_ctn/consultation/start': typeof AppCtnConsultationStartRoute
  '/_app/_ptt/patients/new': typeof AppPttPatientsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboard'
    | '/login'
    | '/logout'
    | '/quit'
    | '/consultations'
    | '/new-user'
    | '/users'
    | '/consultation/$consultationId'
    | '/consultation/start'
    | '/patients/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboard'
    | '/login'
    | '/logout'
    | '/quit'
    | '/consultations'
    | '/new-user'
    | '/users'
    | '/consultation/$consultationId'
    | '/consultation/start'
    | '/patients/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/_ctn'
    | '/_app/_ptt'
    | '/_app/_usr'
    | '/_app/dashboard'
    | '/_app/onboard'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_auth/quit'
    | '/_app/_ctn/consultations'
    | '/_app/_usr/new-user'
    | '/_app/_usr/users'
    | '/_app/_ctn/consultation/$consultationId'
    | '/_app/_ctn/consultation/start'
    | '/_app/_ptt/patients/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_ctn': {
      id: '/_app/_ctn'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppCtnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_ptt': {
      id: '/_app/_ptt'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPttRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_usr': {
      id: '/_app/_usr'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppUsrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboard': {
      id: '/_app/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quit': {
      id: '/_auth/quit'
      path: '/quit'
      fullPath: '/quit'
      preLoaderRoute: typeof AuthQuitRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/_ctn/consultations': {
      id: '/_app/_ctn/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AppCtnConsultationsRouteImport
      parentRoute: typeof AppCtnRoute
    }
    '/_app/_usr/new-user': {
      id: '/_app/_usr/new-user'
      path: '/new-user'
      fullPath: '/new-user'
      preLoaderRoute: typeof AppUsrNewUserRouteImport
      parentRoute: typeof AppUsrRoute
    }
    '/_app/_usr/users': {
      id: '/_app/_usr/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsrUsersRouteImport
      parentRoute: typeof AppUsrRoute
    }
    '/_app/_ctn/consultation/$consultationId': {
      id: '/_app/_ctn/consultation/$consultationId'
      path: '/consultation/$consultationId'
      fullPath: '/consultation/$consultationId'
      preLoaderRoute: typeof AppCtnConsultationConsultationIdRouteImport
      parentRoute: typeof AppCtnRoute
    }
    '/_app/_ctn/consultation/start': {
      id: '/_app/_ctn/consultation/start'
      path: '/consultation/start'
      fullPath: '/consultation/start'
      preLoaderRoute: typeof AppCtnConsultationStartRouteImport
      parentRoute: typeof AppCtnRoute
    }
    '/_app/_ptt/patients/new': {
      id: '/_app/_ptt/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AppPttPatientsNewRouteImport
      parentRoute: typeof AppPttRoute
    }
  }
}

interface AppCtnRouteChildren {
  AppCtnConsultationsRoute: typeof AppCtnConsultationsRoute
  AppCtnConsultationConsultationIdRoute: typeof AppCtnConsultationConsultationIdRoute
  AppCtnConsultationStartRoute: typeof AppCtnConsultationStartRoute
}

const AppCtnRouteChildren: AppCtnRouteChildren = {
  AppCtnConsultationsRoute: AppCtnConsultationsRoute,
  AppCtnConsultationConsultationIdRoute: AppCtnConsultationConsultationIdRoute,
  AppCtnConsultationStartRoute: AppCtnConsultationStartRoute,
}

const AppCtnRouteWithChildren =
  AppCtnRoute._addFileChildren(AppCtnRouteChildren)

interface AppPttRouteChildren {
  AppPttPatientsNewRoute: typeof AppPttPatientsNewRoute
}

const AppPttRouteChildren: AppPttRouteChildren = {
  AppPttPatientsNewRoute: AppPttPatientsNewRoute,
}

const AppPttRouteWithChildren =
  AppPttRoute._addFileChildren(AppPttRouteChildren)

interface AppUsrRouteChildren {
  AppUsrNewUserRoute: typeof AppUsrNewUserRoute
  AppUsrUsersRoute: typeof AppUsrUsersRoute
}

const AppUsrRouteChildren: AppUsrRouteChildren = {
  AppUsrNewUserRoute: AppUsrNewUserRoute,
  AppUsrUsersRoute: AppUsrUsersRoute,
}

const AppUsrRouteWithChildren =
  AppUsrRoute._addFileChildren(AppUsrRouteChildren)

interface AppRouteChildren {
  AppCtnRoute: typeof AppCtnRouteWithChildren
  AppPttRoute: typeof AppPttRouteWithChildren
  AppUsrRoute: typeof AppUsrRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOnboardRoute: typeof AppOnboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCtnRoute: AppCtnRouteWithChildren,
  AppPttRoute: AppPttRouteWithChildren,
  AppUsrRoute: AppUsrRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOnboardRoute: AppOnboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthQuitRoute: typeof AuthQuitRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthQuitRoute: AuthQuitRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
