/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppConsultationRouteImport } from './routes/_app.consultation'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppNewPatientRouteImport } from './routes/_app.new-patient'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthLogoutRouteImport } from './routes/_auth.logout'
import { Route as AuthQuitRouteImport } from './routes/_auth.quit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConsultationRoute = AppConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNewPatientRoute = AppNewPatientRouteImport.update({
  id: '/new-patient',
  path: '/new-patient',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuitRoute = AuthQuitRouteImport.update({
  id: '/quit',
  path: '/quit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthRouteWithChildren
  '/consultation': typeof AppConsultationRoute
  '/dashboard': typeof AppDashboardRoute
  '/new-patient': typeof AppNewPatientRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/quit': typeof AuthQuitRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthRouteWithChildren
  '/consultation': typeof AppConsultationRoute
  '/dashboard': typeof AppDashboardRoute
  '/new-patient': typeof AppNewPatientRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/quit': typeof AuthQuitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/consultation': typeof AppConsultationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/new-patient': typeof AppNewPatientRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/quit': typeof AuthQuitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultation'
    | '/dashboard'
    | '/new-patient'
    | '/login'
    | '/logout'
    | '/quit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultation'
    | '/dashboard'
    | '/new-patient'
    | '/login'
    | '/logout'
    | '/quit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/consultation'
    | '/_app/dashboard'
    | '/_app/new-patient'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_auth/quit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/consultation': {
      id: '/_app/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof AppConsultationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-patient': {
      id: '/_app/new-patient'
      path: '/new-patient'
      fullPath: '/new-patient'
      preLoaderRoute: typeof AppNewPatientRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quit': {
      id: '/_auth/quit'
      path: '/quit'
      fullPath: '/quit'
      preLoaderRoute: typeof AuthQuitRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AppRouteChildren {
  AppConsultationRoute: typeof AppConsultationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewPatientRoute: typeof AppNewPatientRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConsultationRoute: AppConsultationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNewPatientRoute: AppNewPatientRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthQuitRoute: typeof AuthQuitRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthQuitRoute: AuthQuitRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
