// Code generated by ent, DO NOT EDIT.

package patient

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldMaritalStatus holds the string denoting the marital_status field in the database.
	FieldMaritalStatus = "marital_status"
	// FieldDob holds the string denoting the dob field in the database.
	FieldDob = "dob"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldKnownAllergies holds the string denoting the known_allergies field in the database.
	FieldKnownAllergies = "known_allergies"
	// FieldPreExistingConditions holds the string denoting the pre_existing_conditions field in the database.
	FieldPreExistingConditions = "pre_existing_conditions"
	// EdgeConsultations holds the string denoting the consultations edge name in mutations.
	EdgeConsultations = "consultations"
	// Table holds the table name of the patient in the database.
	Table = "patients"
	// ConsultationsTable is the table that holds the consultations relation/edge.
	ConsultationsTable = "consultations"
	// ConsultationsInverseTable is the table name for the Consultation entity.
	// It exists in this package in order to avoid circular dependency with the "consultation" package.
	ConsultationsInverseTable = "consultations"
	// ConsultationsColumn is the table column denoting the consultations relation/edge.
	ConsultationsColumn = "patient_id"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldPhoneNumber,
	FieldGender,
	FieldMaritalStatus,
	FieldDob,
	FieldEmail,
	FieldKnownAllergies,
	FieldPreExistingConditions,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	PhoneNumberValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Gender defines the type for the "gender" enum field.
type Gender string

// GenderUnspecified is the default value of the Gender enum.
const DefaultGender = GenderUnspecified

// Gender values.
const (
	GenderMale        Gender = "male"
	GenderFemale      Gender = "female"
	GenderUnspecified Gender = "unspecified"
)

func (ge Gender) String() string {
	return string(ge)
}

// GenderValidator is a validator for the "gender" field enum values. It is called by the builders before save.
func GenderValidator(ge Gender) error {
	switch ge {
	case GenderMale, GenderFemale, GenderUnspecified:
		return nil
	default:
		return fmt.Errorf("patient: invalid enum value for gender field: %q", ge)
	}
}

// MaritalStatus defines the type for the "marital_status" enum field.
type MaritalStatus string

// MaritalStatusUnspecified is the default value of the MaritalStatus enum.
const DefaultMaritalStatus = MaritalStatusUnspecified

// MaritalStatus values.
const (
	MaritalStatusMarried     MaritalStatus = "married"
	MaritalStatusSingle      MaritalStatus = "single"
	MaritalStatusUnspecified MaritalStatus = "unspecified"
)

func (ms MaritalStatus) String() string {
	return string(ms)
}

// MaritalStatusValidator is a validator for the "marital_status" field enum values. It is called by the builders before save.
func MaritalStatusValidator(ms MaritalStatus) error {
	switch ms {
	case MaritalStatusMarried, MaritalStatusSingle, MaritalStatusUnspecified:
		return nil
	default:
		return fmt.Errorf("patient: invalid enum value for marital_status field: %q", ms)
	}
}

// OrderOption defines the ordering options for the Patient queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPhoneNumber orders the results by the phone_number field.
func ByPhoneNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneNumber, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByMaritalStatus orders the results by the marital_status field.
func ByMaritalStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaritalStatus, opts...).ToFunc()
}

// ByDob orders the results by the dob field.
func ByDob(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDob, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByKnownAllergies orders the results by the known_allergies field.
func ByKnownAllergies(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKnownAllergies, opts...).ToFunc()
}

// ByPreExistingConditions orders the results by the pre_existing_conditions field.
func ByPreExistingConditions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreExistingConditions, opts...).ToFunc()
}

// ByConsultationsCount orders the results by consultations count.
func ByConsultationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConsultationsStep(), opts...)
	}
}

// ByConsultations orders the results by consultations terms.
func ByConsultations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsultationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newConsultationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsultationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ConsultationsTable, ConsultationsColumn),
	)
}
