// Code generated by ent, DO NOT EDIT.

package patient

import (
	"kmed/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldName, v))
}

// PhoneNumber applies equality check predicate on the "phone_number" field. It's identical to PhoneNumberEQ.
func PhoneNumber(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldPhoneNumber, v))
}

// Dob applies equality check predicate on the "dob" field. It's identical to DobEQ.
func Dob(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldDob, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldEmail, v))
}

// KnownAllergies applies equality check predicate on the "known_allergies" field. It's identical to KnownAllergiesEQ.
func KnownAllergies(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldKnownAllergies, v))
}

// PreExistingConditions applies equality check predicate on the "pre_existing_conditions" field. It's identical to PreExistingConditionsEQ.
func PreExistingConditions(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldPreExistingConditions, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContainsFold(FieldName, v))
}

// PhoneNumberEQ applies the EQ predicate on the "phone_number" field.
func PhoneNumberEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldPhoneNumber, v))
}

// PhoneNumberNEQ applies the NEQ predicate on the "phone_number" field.
func PhoneNumberNEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldPhoneNumber, v))
}

// PhoneNumberIn applies the In predicate on the "phone_number" field.
func PhoneNumberIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldPhoneNumber, vs...))
}

// PhoneNumberNotIn applies the NotIn predicate on the "phone_number" field.
func PhoneNumberNotIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldPhoneNumber, vs...))
}

// PhoneNumberGT applies the GT predicate on the "phone_number" field.
func PhoneNumberGT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldPhoneNumber, v))
}

// PhoneNumberGTE applies the GTE predicate on the "phone_number" field.
func PhoneNumberGTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldPhoneNumber, v))
}

// PhoneNumberLT applies the LT predicate on the "phone_number" field.
func PhoneNumberLT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldPhoneNumber, v))
}

// PhoneNumberLTE applies the LTE predicate on the "phone_number" field.
func PhoneNumberLTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldPhoneNumber, v))
}

// PhoneNumberContains applies the Contains predicate on the "phone_number" field.
func PhoneNumberContains(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContains(FieldPhoneNumber, v))
}

// PhoneNumberHasPrefix applies the HasPrefix predicate on the "phone_number" field.
func PhoneNumberHasPrefix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasPrefix(FieldPhoneNumber, v))
}

// PhoneNumberHasSuffix applies the HasSuffix predicate on the "phone_number" field.
func PhoneNumberHasSuffix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasSuffix(FieldPhoneNumber, v))
}

// PhoneNumberIsNil applies the IsNil predicate on the "phone_number" field.
func PhoneNumberIsNil() predicate.Patient {
	return predicate.Patient(sql.FieldIsNull(FieldPhoneNumber))
}

// PhoneNumberNotNil applies the NotNil predicate on the "phone_number" field.
func PhoneNumberNotNil() predicate.Patient {
	return predicate.Patient(sql.FieldNotNull(FieldPhoneNumber))
}

// PhoneNumberEqualFold applies the EqualFold predicate on the "phone_number" field.
func PhoneNumberEqualFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEqualFold(FieldPhoneNumber, v))
}

// PhoneNumberContainsFold applies the ContainsFold predicate on the "phone_number" field.
func PhoneNumberContainsFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContainsFold(FieldPhoneNumber, v))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v Gender) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldGender, v))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v Gender) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldGender, v))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...Gender) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldGender, vs...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...Gender) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldGender, vs...))
}

// MaritalStatusEQ applies the EQ predicate on the "marital_status" field.
func MaritalStatusEQ(v MaritalStatus) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldMaritalStatus, v))
}

// MaritalStatusNEQ applies the NEQ predicate on the "marital_status" field.
func MaritalStatusNEQ(v MaritalStatus) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldMaritalStatus, v))
}

// MaritalStatusIn applies the In predicate on the "marital_status" field.
func MaritalStatusIn(vs ...MaritalStatus) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldMaritalStatus, vs...))
}

// MaritalStatusNotIn applies the NotIn predicate on the "marital_status" field.
func MaritalStatusNotIn(vs ...MaritalStatus) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldMaritalStatus, vs...))
}

// DobEQ applies the EQ predicate on the "dob" field.
func DobEQ(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldDob, v))
}

// DobNEQ applies the NEQ predicate on the "dob" field.
func DobNEQ(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldDob, v))
}

// DobIn applies the In predicate on the "dob" field.
func DobIn(vs ...time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldDob, vs...))
}

// DobNotIn applies the NotIn predicate on the "dob" field.
func DobNotIn(vs ...time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldDob, vs...))
}

// DobGT applies the GT predicate on the "dob" field.
func DobGT(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldDob, v))
}

// DobGTE applies the GTE predicate on the "dob" field.
func DobGTE(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldDob, v))
}

// DobLT applies the LT predicate on the "dob" field.
func DobLT(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldDob, v))
}

// DobLTE applies the LTE predicate on the "dob" field.
func DobLTE(v time.Time) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldDob, v))
}

// DobIsNil applies the IsNil predicate on the "dob" field.
func DobIsNil() predicate.Patient {
	return predicate.Patient(sql.FieldIsNull(FieldDob))
}

// DobNotNil applies the NotNil predicate on the "dob" field.
func DobNotNil() predicate.Patient {
	return predicate.Patient(sql.FieldNotNull(FieldDob))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.Patient {
	return predicate.Patient(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.Patient {
	return predicate.Patient(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContainsFold(FieldEmail, v))
}

// KnownAllergiesEQ applies the EQ predicate on the "known_allergies" field.
func KnownAllergiesEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldKnownAllergies, v))
}

// KnownAllergiesNEQ applies the NEQ predicate on the "known_allergies" field.
func KnownAllergiesNEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldKnownAllergies, v))
}

// KnownAllergiesIn applies the In predicate on the "known_allergies" field.
func KnownAllergiesIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldKnownAllergies, vs...))
}

// KnownAllergiesNotIn applies the NotIn predicate on the "known_allergies" field.
func KnownAllergiesNotIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldKnownAllergies, vs...))
}

// KnownAllergiesGT applies the GT predicate on the "known_allergies" field.
func KnownAllergiesGT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldKnownAllergies, v))
}

// KnownAllergiesGTE applies the GTE predicate on the "known_allergies" field.
func KnownAllergiesGTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldKnownAllergies, v))
}

// KnownAllergiesLT applies the LT predicate on the "known_allergies" field.
func KnownAllergiesLT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldKnownAllergies, v))
}

// KnownAllergiesLTE applies the LTE predicate on the "known_allergies" field.
func KnownAllergiesLTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldKnownAllergies, v))
}

// KnownAllergiesContains applies the Contains predicate on the "known_allergies" field.
func KnownAllergiesContains(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContains(FieldKnownAllergies, v))
}

// KnownAllergiesHasPrefix applies the HasPrefix predicate on the "known_allergies" field.
func KnownAllergiesHasPrefix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasPrefix(FieldKnownAllergies, v))
}

// KnownAllergiesHasSuffix applies the HasSuffix predicate on the "known_allergies" field.
func KnownAllergiesHasSuffix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasSuffix(FieldKnownAllergies, v))
}

// KnownAllergiesIsNil applies the IsNil predicate on the "known_allergies" field.
func KnownAllergiesIsNil() predicate.Patient {
	return predicate.Patient(sql.FieldIsNull(FieldKnownAllergies))
}

// KnownAllergiesNotNil applies the NotNil predicate on the "known_allergies" field.
func KnownAllergiesNotNil() predicate.Patient {
	return predicate.Patient(sql.FieldNotNull(FieldKnownAllergies))
}

// KnownAllergiesEqualFold applies the EqualFold predicate on the "known_allergies" field.
func KnownAllergiesEqualFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEqualFold(FieldKnownAllergies, v))
}

// KnownAllergiesContainsFold applies the ContainsFold predicate on the "known_allergies" field.
func KnownAllergiesContainsFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContainsFold(FieldKnownAllergies, v))
}

// PreExistingConditionsEQ applies the EQ predicate on the "pre_existing_conditions" field.
func PreExistingConditionsEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEQ(FieldPreExistingConditions, v))
}

// PreExistingConditionsNEQ applies the NEQ predicate on the "pre_existing_conditions" field.
func PreExistingConditionsNEQ(v string) predicate.Patient {
	return predicate.Patient(sql.FieldNEQ(FieldPreExistingConditions, v))
}

// PreExistingConditionsIn applies the In predicate on the "pre_existing_conditions" field.
func PreExistingConditionsIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldIn(FieldPreExistingConditions, vs...))
}

// PreExistingConditionsNotIn applies the NotIn predicate on the "pre_existing_conditions" field.
func PreExistingConditionsNotIn(vs ...string) predicate.Patient {
	return predicate.Patient(sql.FieldNotIn(FieldPreExistingConditions, vs...))
}

// PreExistingConditionsGT applies the GT predicate on the "pre_existing_conditions" field.
func PreExistingConditionsGT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGT(FieldPreExistingConditions, v))
}

// PreExistingConditionsGTE applies the GTE predicate on the "pre_existing_conditions" field.
func PreExistingConditionsGTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldGTE(FieldPreExistingConditions, v))
}

// PreExistingConditionsLT applies the LT predicate on the "pre_existing_conditions" field.
func PreExistingConditionsLT(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLT(FieldPreExistingConditions, v))
}

// PreExistingConditionsLTE applies the LTE predicate on the "pre_existing_conditions" field.
func PreExistingConditionsLTE(v string) predicate.Patient {
	return predicate.Patient(sql.FieldLTE(FieldPreExistingConditions, v))
}

// PreExistingConditionsContains applies the Contains predicate on the "pre_existing_conditions" field.
func PreExistingConditionsContains(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContains(FieldPreExistingConditions, v))
}

// PreExistingConditionsHasPrefix applies the HasPrefix predicate on the "pre_existing_conditions" field.
func PreExistingConditionsHasPrefix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasPrefix(FieldPreExistingConditions, v))
}

// PreExistingConditionsHasSuffix applies the HasSuffix predicate on the "pre_existing_conditions" field.
func PreExistingConditionsHasSuffix(v string) predicate.Patient {
	return predicate.Patient(sql.FieldHasSuffix(FieldPreExistingConditions, v))
}

// PreExistingConditionsIsNil applies the IsNil predicate on the "pre_existing_conditions" field.
func PreExistingConditionsIsNil() predicate.Patient {
	return predicate.Patient(sql.FieldIsNull(FieldPreExistingConditions))
}

// PreExistingConditionsNotNil applies the NotNil predicate on the "pre_existing_conditions" field.
func PreExistingConditionsNotNil() predicate.Patient {
	return predicate.Patient(sql.FieldNotNull(FieldPreExistingConditions))
}

// PreExistingConditionsEqualFold applies the EqualFold predicate on the "pre_existing_conditions" field.
func PreExistingConditionsEqualFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldEqualFold(FieldPreExistingConditions, v))
}

// PreExistingConditionsContainsFold applies the ContainsFold predicate on the "pre_existing_conditions" field.
func PreExistingConditionsContainsFold(v string) predicate.Patient {
	return predicate.Patient(sql.FieldContainsFold(FieldPreExistingConditions, v))
}

// HasConsultations applies the HasEdge predicate on the "consultations" edge.
func HasConsultations() predicate.Patient {
	return predicate.Patient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ConsultationsTable, ConsultationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConsultationsWith applies the HasEdge predicate on the "consultations" edge with a given conditions (other predicates).
func HasConsultationsWith(preds ...predicate.Consultation) predicate.Patient {
	return predicate.Patient(func(s *sql.Selector) {
		step := newConsultationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Patient) predicate.Patient {
	return predicate.Patient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Patient) predicate.Patient {
	return predicate.Patient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Patient) predicate.Patient {
	return predicate.Patient(sql.NotPredicates(p))
}
