// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Consultation is the predicate function for consultation builders.
type Consultation func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
